name: CI
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: test
            shell: bash
            env:
              xxx: ${{ secrets }}
            run: |
              node ./index.js
             